# Generated by Django 4.1.7 on 2023-05-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_family_father_relationship_rank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='father_relationship_rank',
        ),
        migrations.RemoveField(
            model_name='family',
            name='mother_relationship_rank',
        ),
        migrations.RemoveField(
            model_name='family',
            name='relationship',
        ),
        migrations.AlterField(
            model_name='family',
            name='father',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='mother',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
